version: '3'
services:
  database:
    image: "postgres"
    ports:
      - "5434:5432"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
  zookeeper:
    image: wurstmeister/zookeeper
 
  kafka:
    image: wurstmeister/kafka
    ports:
        - "9092:9092"
    environment:
       KAFKA_ADVERTISED_HOST_NAME: localhost
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
volumes:
  database-data:
